### ISSUE TITLE
Нарушение пользовательского соглашения

### ISSUE THREAD

**Issue by mono-oleg** [Sominemo/Mono-PWA#110]
Здравствуйте. 
К сожалению, использование неофициальных клиентов банка "Монобанк", включая модифицированные офиицальные, запрещено пользовательским соглашением.
Поэтому нам следует вас предупредить, что банк вправе отказать вам в обслуживании за нарушение пользовательского соглашения.
Мы ждем действий с вашей стороны.

**Comment by Sominemo** [comment]
Закрыто по причине:
- Фейк, не подтверждённый представителями банка
- В приложении используется официальное API, зарегистрированное в платформе корпоративного API
