### ISSUE TITLE
Вы опубликовали приватный ключ

### ISSUE THREAD

**Issue by ghost** [Sominemo/Mono-PWA#113]
Здравствуйте.

Вы опубликовали приватный ключ:
https://github.com/Sominemo/Mono-PWA/blob/9f135ccbe82bbdddfba9c7844ed3b5f4a08ab1e6/webpack/scripts/ssl/server.key

Это очень опасно.

**Comment by Sominemo** [comment]
Это не приватный ключ, а самоподписанный SSL сертификат для тестового окружения, в его публикации нет риска.
